version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9001:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
    depends_on:
      - kafka

  outbox-worker:
    build:
      context: ./service-a-grpc
      dockerfile: Dockerfile.worker
    depends_on:
      - kafka
    volumes:
      - ./service-a-grpc/outbox.db:/app/outbox.db
    environment:
      KAFKA_BROKER: kafka:9092

  service-a-grpc:
    build:
      context: ./service-a-grpc
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - kafka
    volumes:
      - ./service-a-grpc/outbox.db:/app/outbox.db
    environment:
      KAFKA_BROKER: kafka:9092

  service-b-rest:
    build:
      context: ./service-b-rest
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    volumes:
      - ./service-b-rest/total.txt:/app/total.txt
    environment:
      KAFKA_BROKER: kafka:9092

  service-b-consumer:
    build:
      context: ./service-b-rest
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./service-b-rest/total.txt:/app/total.txt
    environment:
      KAFKA_BROKER: kafka:9092
    command: ["ts-node", "src/consumer.ts"]

