# Base image
FROM node:18

# Working directory
WORKDIR /app

# Copy files
COPY package*.json ./
COPY tsconfig.json ./
COPY ./src ./src
COPY ./proto ./proto

# Install dependencies
RUN npm install

# Install ts-node globally
RUN npm install -g ts-node

# Command to run worker
CMD ["ts-node", "src/outboxWorker.ts"]
